import { ArrowRight, CalendarBlank, MapPin, Phone, ShieldCheck, Sparkle, Stethoscope, Tooth } from "@phosphor-icons/react/dist/ssr";
import Image from "next/image";
import Link from "next/link";
import { ChatWidget } from "@/components/chat-widget";
import { Reveal } from "@/components/reveal";

const services = [
  ["Everyday dentistry", "Exams, digital X-rays, gentle hygiene, fillings, and restorative care.", Tooth],
  ["Orthodontics", "Braces and clear aligner planning for teens and adults, thoughtfully mapped.", Sparkle],
  ["Care for children", "Preventive, patient-first visits that make young patients feel at ease.", ShieldCheck],
  ["Urgent appointments", "Support for pain, broken teeth, swelling, and lost fillings during clinic hours.", Stethoscope],
] as const;

export default function Home() {
  return <><header className="mx-auto flex h-[72px] max-w-[1400px] items-center justify-between px-5 sm:px-8 lg:px-12"><Link href="#top" className="font-display text-lg font-semibold tracking-[-0.04em]">Bright Smile <span className="text-accent">Dental</span></Link><nav className="hidden gap-7 text-sm text-text-muted md:flex"><a href="#services">Care</a><a href="#doctors">Doctors</a><a href="#visit">Visit us</a></nav><a href="#visit" className="inline-flex h-10 items-center rounded-full bg-accent px-4 text-sm font-semibold text-white transition duration-150 ease-out hover:-translate-y-0.5 hover:bg-accent-hover active:scale-[0.98]">Request a visit</a></header>
    <main id="top" className="overflow-x-clip"><section className="mx-auto grid min-h-[calc(100dvh-72px)] max-w-[1400px] items-center gap-10 px-5 py-10 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-5"><Reveal><p className="mb-6 text-sm font-semibold tracking-wide text-accent">DENTAL CARE, MADE CALMER</p><h1 className="max-w-[11ch] font-display text-[clamp(3.6rem,7vw,6.8rem)] font-semibold leading-[0.93] tracking-[-0.075em]">Feel at ease in your own smile.</h1><p className="mt-7 max-w-md text-lg leading-8 text-text-muted">Modern dental care for Islamabad, delivered with clear guidance and a gentler pace.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#visit" className="inline-flex h-12 items-center gap-2 rounded-full bg-accent px-5 text-sm font-semibold text-white transition duration-150 ease-out hover:-translate-y-0.5 hover:bg-accent-hover active:scale-[0.98]"><CalendarBlank size={18} weight="bold" /> Request a visit</a><a href="#services" className="inline-flex h-12 items-center gap-2 rounded-full border bg-surface-raised px-5 text-sm font-semibold transition hover:bg-surface">Explore care <ArrowRight size={17} /></a></div></Reveal></div><Reveal delay={0.12} className="lg:col-span-7 lg:pl-8"><div className="relative aspect-[4/3] overflow-hidden rounded-panel bg-surface shadow-panel"><Image src="/images/clinic-consultation.png" alt="A Bright Smile Dental clinician explaining care to a patient" fill priority sizes="(min-width: 1024px) 58vw, 100vw" className="object-cover" /><div className="absolute bottom-4 left-4 max-w-[15rem] rounded-control border border-white/35 bg-white/85 p-4 backdrop-blur-sm"><p className="text-xs font-semibold tracking-wide text-accent">OPEN MONDAY TO SATURDAY</p><p className="mt-1 text-sm font-medium">Simple answers. Thoughtful care. No rush.</p></div></div></Reveal></section>
      <section id="services" className="border-y bg-surface"><div className="mx-auto max-w-[1400px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><Reveal><p className="text-sm font-semibold tracking-wide text-accent">THE CARE YOU NEED</p><h2 className="mt-5 max-w-2xl font-display text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">A plan that starts with listening.</h2></Reveal><div className="mt-12 grid gap-x-10 lg:grid-cols-2">{services.map(([title, detail, Icon], i) => <Reveal key={title} delay={i * 0.06}><article className="flex gap-5 border-t py-7"><span className="grid size-11 shrink-0 place-items-center rounded-control border bg-surface-raised text-accent"><Icon size={22} weight="duotone" /></span><div><h3 className="font-display text-2xl font-semibold tracking-[-0.04em]">{title}</h3><p className="mt-2 max-w-sm leading-7 text-text-muted">{detail}</p></div></article></Reveal>)}</div></div></section>
      <section id="doctors" className="mx-auto grid max-w-[1400px] gap-10 px-5 py-20 sm:px-8 lg:grid-cols-12 lg:px-12 lg:py-32"><Reveal className="lg:col-span-5"><div className="relative aspect-[4/5] overflow-hidden rounded-panel"><Image src="/images/dental-team.png" alt="The dental team at Bright Smile Dental" fill sizes="(min-width: 1024px) 42vw, 100vw" className="object-cover" /></div></Reveal><div className="flex flex-col justify-center lg:col-span-6 lg:col-start-7"><Reveal><p className="text-sm font-semibold tracking-wide text-accent">MEET THE CLINICIANS</p><h2 className="mt-5 font-display text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Expertise with a human point of view.</h2><div className="mt-10 space-y-7"><article className="border-t pt-5"><h3 className="font-display text-2xl font-semibold">Dr. Ayesha Khan</h3><p className="mt-1 text-sm font-medium text-accent">Orthodontic clinician</p><p className="mt-3 leading-7 text-text-muted">Braces and clear aligner planning for teens and adults.</p></article><article className="border-t pt-5"><h3 className="font-display text-2xl font-semibold">Dr. Omar Siddiqui</h3><p className="mt-1 text-sm font-medium text-accent">General dentist</p><p className="mt-3 leading-7 text-text-muted">Preventive treatment, restorative care, and urgent dental assessments.</p></article></div></Reveal></div></section>
      <section className="mx-auto max-w-[1400px] px-5 pb-20 sm:px-8 lg:px-12 lg:pb-32"><Reveal><div className="rounded-panel bg-text-primary px-6 py-12 text-background sm:px-10 lg:grid lg:grid-cols-12 lg:items-end lg:px-14 lg:py-16"><div className="lg:col-span-7"><p className="text-sm font-semibold tracking-wide text-[#9fd0c8]">HOW A VISIT FEELS</p><h2 className="mt-5 font-display text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Clear next steps, from first question to follow-up.</h2></div><div className="mt-8 space-y-4 text-sm leading-6 text-[#c8d1cd] lg:col-span-4 lg:col-start-9 lg:mt-0"><p>01. Tell us what you need in a short booking request.</p><p>02. We confirm a time that fits your care plan.</p><p>03. Leave with a clear understanding of what comes next.</p></div></div></Reveal></section>
      <section className="border-y bg-surface"><div className="mx-auto max-w-[1400px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><Reveal><h2 className="font-display text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Care that patients recommend.</h2></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3"><Quote quote="The explanation was clear and I never felt hurried." name="Sana M." detail="General dentistry patient" /><Quote quote="My son settled in quickly. The appointment felt calm from start to finish." name="Fariha A." detail="Parent of a pediatric patient" /><Quote quote="I knew exactly what my orthodontic options were before deciding." name="Hassan R." detail="Orthodontic patient" /></div></div></section>
      <section id="visit" className="mx-auto max-w-[1400px] px-5 py-20 sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-10 lg:grid-cols-12"><Reveal className="lg:col-span-6"><p className="text-sm font-semibold tracking-wide text-accent">VISIT BRIGHT SMILE</p><h2 className="mt-5 font-display text-4xl font-semibold tracking-[-0.055em] sm:text-5xl">Easy to find in the heart of Islamabad.</h2><a href="#top" className="mt-8 inline-flex h-12 items-center gap-2 rounded-full bg-accent px-5 text-sm font-semibold text-white transition hover:bg-accent-hover">Talk with the clinic assistant <ArrowRight size={17} /></a></Reveal><Reveal delay={0.08} className="lg:col-span-5 lg:col-start-8"><div className="space-y-6 rounded-panel border bg-surface-raised p-7"><div className="flex gap-4"><MapPin size={22} className="shrink-0 text-accent" weight="duotone" /><p className="leading-7 text-text-muted">Suite 402, 4th Floor, F-7 Markaz<br />Jinnah Super Market, Islamabad</p></div><div className="flex gap-4 border-t pt-6"><CalendarBlank size={22} className="shrink-0 text-accent" weight="duotone" /><p className="leading-7 text-text-muted">Monday to Saturday<br />10:00 AM to 8:00 PM</p></div><div className="flex gap-4 border-t pt-6"><Phone size={22} className="shrink-0 text-accent" weight="duotone" /><p className="leading-7 text-text-muted">Walk-ins are welcome for urgent concerns when a clinician is available.</p></div></div></Reveal></div></section></main><footer className="border-t"><div className="mx-auto flex max-w-[1400px] flex-col gap-4 px-5 py-8 text-sm text-text-muted sm:flex-row sm:justify-between sm:px-8 lg:px-12"><p>Bright Smile Dental, Islamabad</p><p>Thoughtful care for every smile.</p></div></footer><ChatWidget /></>;
}
function Quote({ quote, name, detail }: { quote: string; name: string; detail: string }) { return <Reveal><figure className="flex min-h-56 flex-col justify-between rounded-panel border bg-surface-raised p-7"><blockquote className="font-display text-2xl font-semibold leading-tight tracking-[-0.035em]">“{quote}”</blockquote><figcaption className="mt-8 text-sm"><p className="font-semibold">{name}</p><p className="mt-1 text-text-muted">{detail}</p></figcaption></figure></Reveal>; }
