"use client";

import Image from "next/image";
import { motion, AnimatePresence, useReducedMotion } from "motion/react";
import { Baby, FirstAid, ShieldCheck, Tooth } from "@phosphor-icons/react";
import { useState } from "react";
import { PageNav } from "@/components/page-nav";
import { ChatWidget } from "@/components/chat-widget";

const tabs = [
  { title: "Preventive & restorative", icon: Tooth, image: "/images/real-examination.jpeg", label: "Examination and hygiene", copy: "A comprehensive oral examination is where we begin. From hygiene appointments and digital radiographs to composite fillings and restorative options, you see the clinical picture before choosing a treatment path.", items: ["Oral examination", "Digital radiographs when indicated", "Hygiene and gum-health support", "Composite restorations"] },
  { title: "Orthodontic assessment", icon: ShieldCheck, image: "/images/real-xray-consult.jpeg", label: "Diagnostic review", copy: "For braces and clear aligners, diagnostic records turn a broad idea into a considered plan. We explain the sequence, the options, and what each stage is for.", items: ["Braces planning", "Clear aligner planning", "Diagnostic records", "Treatment-stage guidance"] },
  { title: "Paediatric visits", icon: Baby, image: "/images/real-chairside.jpeg", label: "A gentler introduction", copy: "Young patients deserve time to get familiar with the room, the tools, and the team. Visits move at a comfortable pace with prevention at the centre.", items: ["First dental visits", "Preventive guidance", "Hygiene habits", "Patient-paced appointments"] },
  { title: "Urgent concerns", icon: FirstAid, image: "/images/real-exam.jpeg", label: "A clear next step", copy: "Dental pain, swelling, fractured teeth, and lost fillings can feel urgent. During clinic hours, the team can help triage the concern and guide the next appropriate step.", items: ["Toothache", "Swelling", "Fractured teeth", "Lost fillings"] },
];

export function CarePage() {
  const [active, setActive] = useState(0); const reduce = useReducedMotion(); const item = tabs[active]; const Icon = item.icon;
  return <main className="min-h-screen bg-paper text-pine"><PageNav /><section className="mx-auto grid max-w-[1540px] gap-10 px-5 py-16 md:px-10 lg:grid-cols-12 lg:py-24"><div className="lg:col-span-7"><p className="section-kicker text-teal">CLINICAL CARE, CLEARLY EXPLAINED</p><h1 className="mt-5 font-display text-[clamp(4rem,8vw,8.8rem)] font-semibold leading-[.82] tracking-[-.1em]">Care that starts with the <i>whole picture.</i></h1><p className="mt-8 max-w-xl text-lg leading-8 text-pine/70">Select an area of care to see the kinds of questions we can help with and how an appointment is approached.</p></div><div className="relative min-h-[300px] overflow-hidden rounded-[2rem_2rem_2rem_7rem] bg-mint lg:col-span-4 lg:col-start-9"><Image src="/images/real-tablet-consult.jpeg" alt="A dentist reviewing dental information with a patient" fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 34vw" /></div></section><section className="bg-pine px-5 py-14 text-paper md:px-10 md:py-20"><div className="mx-auto max-w-[1540px]"><div className="flex gap-2 overflow-x-auto pb-5">{tabs.map((tab,index)=>{const TabIcon=tab.icon; return <button key={tab.title} onClick={()=>setActive(index)} className={`flex shrink-0 items-center gap-2 rounded-full px-4 py-3 text-sm font-semibold transition-all duration-300 ${active===index?"bg-mango text-pine":"bg-paper/10 text-paper/70 hover:bg-paper/20"}`}><TabIcon size={18} weight="duotone" />{tab.title}</button>})}</div><div className="grid gap-10 border-t border-paper/15 pt-10 lg:grid-cols-12 lg:items-center"><div className="lg:col-span-5"><AnimatePresence mode="wait"><motion.div key={item.title} initial={reduce?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.45,ease:[.16,1,.3,1]}}><div className="flex size-12 items-center justify-center rounded-2xl bg-mango text-pine"><Icon size={25} weight="duotone" /></div><p className="mt-7 text-xs font-bold tracking-[.15em] text-mango">{item.label.toUpperCase()}</p><h2 className="mt-3 font-display text-5xl font-semibold leading-[.9] tracking-[-.08em]">{item.title}</h2><p className="mt-6 max-w-xl leading-8 text-paper/70">{item.copy}</p><ul className="mt-8 grid gap-3 text-sm font-semibold text-paper/85">{item.items.map(value=><li className="flex items-center gap-3" key={value}><span className="size-1.5 rounded-full bg-mango" />{value}</li>)}</ul></motion.div></AnimatePresence></div><div className="relative aspect-[1.2/1] overflow-hidden rounded-[2rem] bg-mint lg:col-span-6 lg:col-start-7"><AnimatePresence mode="wait"><motion.div key={item.image} initial={reduce?false:{scale:1.08,opacity:0}} animate={{scale:1,opacity:1}} exit={{scale:1.04,opacity:0}} transition={{duration:.6,ease:[.16,1,.3,1]}} className="absolute inset-0"><Image src={item.image} alt={item.label} fill className="object-cover" sizes="(max-width: 1024px) 100vw, 50vw" /></motion.div></AnimatePresence></div></div></div></section><ChatWidget /></main>;
}
