import Image from "next/image";
import { ArrowUpRight, Crosshair } from "@phosphor-icons/react/dist/ssr";
import { PageNav } from "@/components/page-nav";
import { ChatWidget } from "@/components/chat-widget";

export default function TeamPage() {
  return <main className="min-h-screen bg-paper text-pine"><PageNav /><section className="mx-auto max-w-[1540px] px-5 py-16 md:px-10 md:py-24"><p className="section-kicker text-teal">THE PEOPLE BEHIND THE PLAN</p><div className="mt-5 grid gap-10 lg:grid-cols-12 lg:items-end"><h1 className="font-display text-[clamp(4rem,8.5vw,9rem)] font-semibold leading-[.81] tracking-[-.105em] lg:col-span-8">Clinical focus.<br /><i>Human presence.</i></h1><p className="max-w-sm text-lg leading-8 text-pine/70 lg:col-span-3 lg:col-start-10">The best care is not just technical. It is the space to ask, understand, and choose with confidence.</p></div><div className="mt-16 grid gap-4 md:grid-cols-12"><div className="relative min-h-[400px] overflow-hidden rounded-[3rem_2rem_2rem_2rem] md:col-span-7"><Image src="/images/real-team-xray.jpeg" alt="Dentist reviewing a patient's dental radiograph" fill priority className="object-cover" sizes="(max-width: 768px) 100vw, 58vw" /></div><div className="grid gap-4 md:col-span-5"><div className="relative min-h-[230px] overflow-hidden rounded-[2rem]"><Image src="/images/real-tablet-consult.jpeg" alt="Dental radiograph consultation" fill className="object-cover" sizes="(max-width: 768px) 100vw, 42vw" /></div><div className="bg-mint p-8 rounded-[2rem]"><Crosshair size={29} className="text-coral" weight="duotone" /><p className="mt-8 font-display text-3xl leading-[.95] tracking-[-.06em]">A consultation should make the next step feel simpler.</p></div></div></div></section><section className="bg-pine px-5 py-20 text-paper md:px-10"><div className="mx-auto grid max-w-[1540px] gap-7 md:grid-cols-2"><Clinician number="01" name="Dr. Ayesha Khan" role="Orthodontic clinician" copy="Works with teens and adults on braces and clear-aligner planning, making the diagnostic stage easier to understand." image="/images/real-xray-consult.jpeg" /><Clinician number="02" name="Dr. Omar Siddiqui" role="General dentist" copy="Focuses on preventive examinations, restorative dentistry, and urgent concerns with a calm, considered chairside approach." image="/images/real-examination.jpeg" /></div></section><ChatWidget /></main>;
}
function Clinician({number,name,role,copy,image}:{number:string;name:string;role:string;copy:string;image:string}) { return <article className="group overflow-hidden rounded-[2rem] bg-paper text-pine"><div className="relative aspect-[1.55/1] overflow-hidden"><Image src={image} alt="Dental clinician at work" fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(max-width:768px) 100vw, 50vw" /><span className="absolute left-5 top-5 rounded-full bg-pine px-3 py-2 font-mono text-xs text-paper">{number}</span></div><div className="p-7"><p className="text-xs font-bold tracking-[.15em] text-teal">{role.toUpperCase()}</p><h2 className="mt-3 font-display text-4xl tracking-[-.07em]">{name}</h2><p className="mt-4 max-w-md leading-7 text-pine/65">{copy}</p><a href="/visit#booking" className="mt-7 inline-flex items-center gap-2 text-sm font-bold">Request a visit <ArrowUpRight size={17} /></a></div></article>; }
